version: '3.8'

services:
  flask01:
    image: app:0.3
    environment:
      - APP_NAME=Flask01
    expose:
      - 5000

  flask02:
    image: app:0.3
    environment:
        - APP_NAME=Flask02
    expose:
      - 5000

  redis:
    image: redis
    expose:
      - 6379

  balanceador:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf